Sitegeist:
  Monocle:
    BackstopJS:

      # template for the generated backstop.json file
      # the keys 'id','viewports','scenarios' and 'pathes' are
      # replaced by the backstop:configuration command
      # all other keys can be adjusted as needed
      configurationTemplate:
        # PackageKey of the site-package
        id: null
        # Scenario configuration, created from the styleguide prototypes
        scenarios: null
        # Viewport configuration, created from the configured monocle viewports
        viewports: null
        # The pathes are adjusted for flow
        paths:
          bitmaps_reference: '%FLOW_PATH_ROOT%Test/BackstopJS/References'
          engine_scripts: '%FLOW_PATH_ROOT%Test/BackstopJS/EngineScripts'
          bitmaps_test: '%FLOW_PATH_TEMPORARY%BackstopJS/Test'
          html_report: '%FLOW_PATH_TEMPORARY%BackstopJS/HtmlReport'
          ci_report: '%FLOW_PATH_TEMPORARY%BackstopJS/CiReport'
        onBeforeScript: ''
        onReadyScript: ''
        report:
          - browser
        engine: puppeteer
        engineOptions:
          args:
            - '--no-sandbox'
        asyncCaptureLimit: 5
        asyncCompareLimit: 50
        debug: false
        debugWindow: false

      # template for
      scenarioTemplate:
        # Replaced with prototype name or styleguide title
        label: null
        # Replaced with prototype preview url
        url: null
        cookiePath: ''
        referenceUrl: ''
        readyEvent: ''
        readySelector: ''
        delay: 0
        hideSelectors: { }
        removeSelectors: { }
        hoverSelector: ''
        clickSelector: ''
        postInteractionWait: 0
        selectors: { }
        selectorExpansion: true
        expect: 0
        misMatchThreshold: 0.1
        requireSameDimensions: true
